name: Run Actions

on:
  pull_request:

jobs:
  greetings-action:
    name: Run greetings action  ï¸
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code ğŸ“š
        uses: actions/checkout@v3

      - name: Set up Node ğŸŸ¢
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages âš™ï¸
        run: yarn install --frozen-lockfile

      - name: Build ğŸ—ï¸  ï¸
        run: yarn run prepare-release

      - name: Run action â–¶ï¸
        uses: ./

  labels-action:
    name: Run labels action  ï¸
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code ğŸ“š
        uses: actions/checkout@v3

      - name: Set up Node ğŸŸ¢
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages âš™ï¸
        run: yarn install --frozen-lockfile

      - name: Build ğŸ—ï¸  ï¸
        run: yarn run prepare-release

      - name: Run `labels` action â–¶ï¸
        uses: ./labels
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}