name: Run Action

on:
  pull_request:

jobs:
  build:
    name: Build ğŸ—ï¸  ï¸
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code ğŸ“š
        uses: actions/checkout@v3

      - name: Set up Node ğŸŸ¢
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages âš™ï¸
        run: yarn install --frozen-lockfile

      - name: Build ğŸ—ï¸  ï¸
        run: yarn run prepare-release

      - name: Run greetings action â–¶ï¸
        uses: ./

      - name: Run labels action â–¶ï¸
        uses: ./labels
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


#  run-test:
#    name: Run action â–¶ï¸
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-latest ]
#
#    steps:
#      - name: Checkout code ğŸ“š
#        uses: actions/checkout@v3
#
#      - name: Run my action â–¶ï¸
#        uses: ./
#        with:
#          name: GH user
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
